// src/utils/countryISOCodes.js

// Map country names to ISO 3166-1 alpha-2 codes for flag display
export const countryToISOCode = {
    "Afghanistan": "AF",
    "Albania": "AL",
    "Algeria": "DZ",
    "Angola": "AO",
    "Antarctica": "AQ",
    "Argentina": "AR",
    "Armenia": "AM",
    "Australia": "AU",
    "Austria": "AT",
    "Azerbaijan": "AZ",
    "Bahamas": "BS",
    "Bangladesh": "BD",
    "Belarus": "BY",
    "Belgium": "BE",
    "Belize": "BZ",
    "Benin": "BJ",
    "Bhutan": "BT",
    "Bolivia": "BO",
    "Bosnia and Herz.": "BA",
    "Bosnia & Herzegovina": "BA",
    "Botswana": "BW",
    "Brazil": "BR",
    "Brunei": "BN",
    "Brunei Darussalam": "BN",
    "Bulgaria": "BG",
    "Burkina Faso": "BF",
    "Burundi": "BI",
    "Cambodia": "KH",
    "Cameroon": "CM",
    "Canada": "CA",
    "Central African Rep.": "CF",
    "Central African Republic": "CF",
    "Chad": "TD",
    "Chile": "CL",
    "China": "CN",
    "Colombia": "CO",
    "Congo": "CG",
    "Costa Rica": "CR",
    "Croatia": "HR",
    "Cuba": "CU",
    "Cyprus": "CY",
    "Czechia": "CZ",
    "Czech Republic": "CZ",
    "Côte d'Ivoire": "CI",
    "Ivory Coast": "CI",
    "Dem. Rep. Congo": "CD",
    "Democratic Republic of the Congo": "CD",
    "Denmark": "DK",
    "Djibouti": "DJ",
    "Dominican Rep.": "DO",
    "Dominican Republic": "DO",
    "Ecuador": "EC",
    "Egypt": "EG",
    "El Salvador": "SV",
    "Eq. Guinea": "GQ",
    "Equatorial Guinea": "GQ",
    "Eritrea": "ER",
    "Estonia": "EE",
    "Eswatini": "SZ",
    "Swaziland": "SZ",
    "Ethiopia": "ET",
    "Falkland Is.": "FK",
    "Falkland Islands": "FK",
    "Fiji": "FJ",
    "Finland": "FI",
    "Fr. S. Antarctic Lands": "TF",
    "French Southern Territories": "TF",
    "France": "FR",
    "Gabon": "GA",
    "Gambia": "GM",
    "Georgia": "GE",
    "Germany": "DE",
    "Ghana": "GH",
    "Greece": "GR",
    "Greenland": "GL",
    "Guatemala": "GT",
    "Guinea": "GN",
    "Guinea-Bissau": "GW",
    "Guyana": "GY",
    "Haiti": "HT",
    "Honduras": "HN",
    "Hungary": "HU",
    "Iceland": "IS",
    "India": "IN",
    "Indonesia": "ID",
    "Iran": "IR",
    "Iran (Islamic Republic of)": "IR",
    "Iraq": "IQ",
    "Ireland": "IE",
    "Israel": "IL",
    "Italy": "IT",
    "Jamaica": "JM",
    "Japan": "JP",
    "Jordan": "JO",
    "Kazakhstan": "KZ",
    "Kenya": "KE",
    "Kosovo": "XK", // Not officially ISO but commonly used
    "Kuwait": "KW",
    "Kyrgyzstan": "KG",
    "Laos": "LA",
    "Lao People's Democratic Republic": "LA",
    "Latvia": "LV",
    "Lebanon": "LB",
    "Lesotho": "LS",
    "Liberia": "LR",
    "Libya": "LY",
    "Libyan Arab Jamahiriya": "LY",
    "Lithuania": "LT",
    "Luxembourg": "LU",
    "North Macedonia": "MK",
    "Macedonia": "MK",
    "The former Yugoslav Republic of Macedonia": "MK",
    "Madagascar": "MG",
    "Malawi": "MW",
    "Malaysia": "MY",
    "Mali": "ML",
    "Mauritania": "MR",
    "Mexico": "MX",
    "Moldova": "MD",
    "Moldova, Republic of": "MD",
    "Mongolia": "MN",
    "Montenegro": "ME",
    "Morocco": "MA",
    "Mozambique": "MZ",
    "Myanmar": "MM",
    "Burma": "MM",
    "N. Cyprus": "CY", // Not officially ISO
    "Namibia": "NA",
    "Nepal": "NP",
    "Netherlands": "NL",
    "New Caledonia": "NC",
    "New Zealand": "NZ",
    "Nicaragua": "NI",
    "Niger": "NE",
    "Nigeria": "NG",
    "North Korea": "KP",
    "Democratic People's Republic of Korea": "KP",
    "Norway": "NO",
    "Oman": "OM",
    "Pakistan": "PK",
    "Palestine": "PS",
    "State of Palestine": "PS",
    "Panama": "PA",
    "Papua New Guinea": "PG",
    "Paraguay": "PY",
    "Peru": "PE",
    "Philippines": "PH",
    "Poland": "PL",
    "Portugal": "PT",
    "Puerto Rico": "PR",
    "Qatar": "QA",
    "Romania": "RO",
    "Russia": "RU",
    "Russian Federation": "RU",
    "Rwanda": "RW",
    "S. Sudan": "SS",
    "South Sudan": "SS",
    "Saudi Arabia": "SA",
    "Senegal": "SN",
    "Serbia": "RS",
    "Sierra Leone": "SL",
    "Slovakia": "SK",
    "Slovenia": "SI",
    "Solomon Is.": "SB",
    "Solomon Islands": "SB",
    "Somalia": "SO",
    "Somaliland": "SO", // Not officially ISO
    "South Africa": "ZA",
    "South Korea": "KR",
    "Republic of Korea": "KR",
    "Spain": "ES",
    "Sri Lanka": "LK",
    "Sudan": "SD",
    "Suriname": "SR",
    "Sweden": "SE",
    "Switzerland": "CH",
    "Syria": "SY",
    "Syrian Arab Republic": "SY",
    "Taiwan": "TW",
    "Chinese Taipei": "TW",
    "Tajikistan": "TJ",
    "Tanzania": "TZ",
    "United Republic of Tanzania": "TZ",
    "Thailand": "TH",
    "Timor-Leste": "TL",
    "East Timor": "TL",
    "Togo": "TG",
    "Trinidad and Tobago": "TT",
    "Tunisia": "TN",
    "Turkey": "TR",
    "Türkiye": "TR",
    "Turkmenistan": "TM",
    "Uganda": "UG",
    "Ukraine": "UA",
    "United Arab Emirates": "AE",
    "UAE": "AE",
    "United Kingdom": "GB",
    "U.K. of Great Britain and Northern Ireland": "GB",
    "UK": "GB",
    "Britain": "GB",
    "United States of America": "US",
    "United States": "US",
    "USA": "US",
    "US": "US",
    "Uruguay": "UY",
    "Uzbekistan": "UZ",
    "Vanuatu": "VU",
    "Venezuela": "VE",
    "Vietnam": "VN",
    "W. Sahara": "EH",
    "Western Sahara": "EH",
    "Yemen": "YE",
    "Zambia": "ZM",
    "Zimbabwe": "ZW"
};

// Function to get ISO code from country name
export const getISOCode = (countryName) => {
    if (!countryName) return null;

    // Direct lookup
    if (countryToISOCode[countryName]) {
        return countryToISOCode[countryName];
    }

    // Case-insensitive lookup
    const lowerCountryName = countryName.toLowerCase();
    const match = Object.keys(countryToISOCode).find(
        key => key.toLowerCase() === lowerCountryName
    );

    if (match) {
        return countryToISOCode[match];
    }

    // Partial match (for handling variations)
    const partialMatch = Object.keys(countryToISOCode).find(
        key => key.toLowerCase().includes(lowerCountryName) ||
            lowerCountryName.includes(key.toLowerCase())
    );

    if (partialMatch) {
        return countryToISOCode[partialMatch];
    }

    // Default fallback for common countries not in the map
    const fallbacks = {
        "north macedonia": "MK",
        "macedonia": "MK",
        "russia": "RU",
        "usa": "US",
        "uk": "GB",
        "iran": "IR",
        "syria": "SY",
        "north korea": "KP",
        "south korea": "KR",
        "dr congo": "CD",
        "congo": "CD",
        "ivory coast": "CI"
    };

    return fallbacks[lowerCountryName] || null;
}; 